### PR TITLE
Fix #391: Update ignored dirs and Svelte instructions

### LINKED ISSUE #391: Sveltekit framework support
### Describe the bug

Hi,
I have implemented quarkus quinoa with a sveltekit application that is using vite.
In production mode, everything is working perfectly, but I am not able to make it work in dev mode.

If I put properties:
```properties
quarkus.quinoa.dev-server=true
%dev.quarkus.quinoa.index-page=/
````

I have the following error in console : 
```
Error: Not found: //
at resolve (C:/DEV/snipets/sveltekit-quark/230621-svk3/src/main/webui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:430:13)
```

and I am redirected to quarkus default index.html.

If don't have %dev.quarkus.quinoa.index-page=/ , I have the following error:
```
Error: Not found: /index.html                                                                                                                                                                                                       
    at resolve (C:/DEV/snipets/sveltekit-quark/230621-svk3/src/main/webui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:430:13)
```

As a workaround, I have tried to put sev-server to false but in this case the problem is that sveltekit generate some files in a sveltekit folder in sources during code generation, and these files are deteted by live reload. The compilation is continuously trigered.

I hope I didn't make a mistake, and thanx a lot for your work, this extension is very cool :)

### Quinoa version

2.0.5

### Quarkus version

3.1.2.Final

### Build / Runtime

Vite

### Package Manager

None

### Steps to reproduce the behavior

clone https://github.com/fblan/test-quark/tree/main
`./mvnw package`
`java -jar target/quarkus-app/quarkus-run.jar`
open browser on http://localhost:8080
the application is displayed normally.
click on SVPOSTS and a page is displayed. This page call quarkus rest api. Everything is working perfectly.

start the dev mode:
`
Error: Not found: //
at resolve (C:/DEV/snipets/sveltekit-quark/230621-svk3/src/main/webui/node_modules/@sveltejs/kit/src/runtime/server/respond.js:430:13)

`

### Expected behavior

same behavior than in production mode.

### PR DESCRIPTION
**Pull request by melloware**
Fix #391: Update ignored dirs and Svelte instructions

### CODE REVIEW

**Comment by fblan** [comment]
Thanx a lot!

**Comment by ia3andy** [comment]
@melloware we might be able to replace the scanning by the new predicate (it would make things way simpler): https://github.com/quarkiverse/quarkus-web-bundler/blob/main/deployment/src/main/java/io/quarkiverse/web/bundler/deployment/WebAssetsScannerProcessor.java#L59-L60

**Comment by melloware** [comment]
But that would include all resources under `/webui` right?  And our goal is to exclude things from `webui` to NOT be watched?

**Comment by ia3andy** [comment]
@melloware no it's a predicate to determine what needs a restart based on the location

**Comment by melloware** [comment]
Maybe we can merge this and do it as a follow on PR because i have a feeling that kind of change would require heavier testing???

File: deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/FrameworkType.java [hunk 1]
```diff
@@ -112,6 +112,33 @@ public static DetectedFramework detectFramework(LaunchModeBuildItem launchMode,
...
+     * @param filePath the file path to check
+     * @return true if it is a directory that should be scanned for changes, false if it should be ignored
+     */
+    public static boolean shouldScanPath(Path filePath) {
+        if (!Files.isDirectory(filePath)) {
+            // not a directory so do not scan
+            return false;
+        }
+
+        final StringBuilder regex = new StringBuilder("[.]\\S+|node_modules|target");
```
Comment (ia3andy) [inline deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/FrameworkType.java:129]: instead of appending the framework buildDir, why don't you just add a hard comparison?

That said, I would:
- Keep the static IGNORE_WATCH Set and merge the framework build dirs (static)
- Check if it should be ignored
- Use a static compiled REGEX with `^[.].+$`

**Review by ia3andy — CHANGES_REQUESTED** [review]
Added a small suggestion to make the algo a bit more robust

File: deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/FrameworkType.java (hunk 1 above)
Comment (melloware) [reply deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/FrameworkType.java]: Changes made

**Review by ia3andy — APPROVED** [review]
LGTM
