### PR TITLE
Fix #711: Update Solid Start detection

### LINKED ISSUE #711: SolidJS: update docs for configuration
### Describe the bug

Even using a sample quinoa-app, and doing something similar in a new app, all requests just end up redirecting to the Quarkus development UI, because there is no `index.html` in the `/META-INF/resources` directory. This is coded in Quarkus with no configuration option to disable it, and Quinoa does not override it.  

It is also not clear if custom express middleware is needed as shown in the quinoa-codestart sample:

https://github.com/quarkiverse/quarkus-quinoa/blob/main/runtime/src/main/codestarts/quarkus/quinoa-codestart/base/src/main/webui/vite.config.js#L9

Create app with:

```quarkus create app quinoa-app -x=io.quarkiverse.quinoa:quarkus-quinoa```

And this only works on `http://localhost:8080/quinoa.html` and even if setting the SPA configuration to true still redirects to dev UI at `http://localhost:8080/`

```
quarkus.quinoa.enable-spa-routing=true
```

It just isn't clear how to get index.html working with something like Solid.js or even your sample working from `index.html` (other than `quinoa.html`) 

And again, this create app has all the custom express handling which is not mentioned in the docs at all.  Is it needed?  not needed?

Regardless, can't get `http://localhost:8080/` to work for the hosted webui

### Quinoa version

2.4.1

### Quarkus version

3.12.1

### Build / Runtime

Vite

### Package Manager

PNPM

### Steps to reproduce the behavior

see above

### Expected behavior

`http://localhost:8080/` goes to the webui and not the quarkus dev ui

### PR DESCRIPTION
**Pull request by melloware**
Fix #711: Update Solid Start detection

### CODE REVIEW

File: deployment/src/main/java/io/quarkiverse/quinoa/deployment/framework/FrameworkType.java [hunk 1]
```diff
@@ -41,7 +41,8 @@ public enum FrameworkType {
     VUE_LEGACY(Set.of("vue-cli-service serve"), generic("dist", "serve", 3000)),
     VITE(Set.of("vite"), generic("dist", "dev", 5173)),
     FARM(Set.of("farm"), generic("dist", "dev", 9000)),
-    SOLID_START(Set.of("solid-start dev", "vinxi dev"), generic("dist", "dev", 3000)),
+    SOLID_START_LEGACY(Set.of("solid-start dev"), generic("dist", "dev", 3000)),
+    SOLID_START(Set.of("vinxi dev"), generic("output", "dev", 3000)),
```
Comment (apatrida) [inline deployment/src/main/java/io/quarkiverse/quinoa/deployment/framework/FrameworkType.java:45]: is `.output` not `output`

**Comment by apatrida** [comment]
small error here.  The output dir lf a build command is `.output` not `output` 

Vinxi creates `.vinxi` directory first, and stages new files there as well as server code splitting, then builds `.output` depending on the server plugin being used the final verison for that server there.
