### PR TITLE
DevUI: Logging and Install Button

### LINKED ISSUE #55: Add some control over the dev-server from the dev-ui
🚀🚀🚀

### LINKED ISSUE #296: Can't launch dev mode with Quarkus 3.0.0.CR1
I tried Quinoa version 2.0.0 & 2.0.1. today but Quarkus dev mode using 3.0.0.CR1 is broken. The app won't start, although running `./mvnw clean verify` works fine.

```
2023-03-30 14:11:13,927 INFO  [com.git.eir.mav.plu.fro.lib.NodeInstaller] (build-28) Node v18.14.1 is already installed.
2023-03-30 14:11:13,931 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2023-03-30 14:11:14,111 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkiverse.quinoa.deployment.devui.QuinoaDevUIProcessor#createCard threw an exception: java.lang.NoSuchMethodError: io.quarkus.devui.spi.page.CardPageBuildItem: method 'void <init>(java.lang.String)' not founds [:] for the terminal, [h] for more options>
        at io.quarkiverse.quinoa.deployment.devui.QuinoaDevUIProcessor.createCard(QuinoaDevUIProcessor.java:22)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1512)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)

        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:335)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:86)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:447)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:59)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:149)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:104)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkiverse.quinoa.deployment.devui.QuinoaDevUIProcessor#createCard threw an exception: java.lang.NoSuchMethodError: io.quarkus.devui.spi.page.CardPageBuildItem: method 'void <init>(java.lang.String)' not found
        at io.quarkiverse.quinoa.deployment.devui.QuinoaDevUIProcessor.createCard(QuinoaDevUIProcessor.java:22)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1512)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)

        at io.quarkus.builder.Execution.run(Execution.java:123)
        at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:331)
        ... 9 more
Caused by: java.lang.NoSuchMethodError: io.quarkus.devui.spi.page.CardPageBuildItem: method 'void <init>(java.lang.String)' not found
        at io.quarkiverse.quinoa.deployment.devui.QuinoaDevUIProcessor.createCard(QuinoaDevUIProcessor.java:22)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1512)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

### PR DESCRIPTION
**Pull request by melloware**
Fix #296
Fix #55

Step 1 is created a log console to capture all specific Quinoa logs.  This will allow us to capture the Node stuff when we add install and restart etc later.

image

image

### CODE REVIEW

File: runtime/src/main/java/io/quarkiverse/quinoa/QuinoaDevWebSocketProxyHandler.java [hunk 1]
```diff
@@ -68,7 +68,7 @@ public void handle(final RoutingContext ctx) {
 
                 httpClient.webSocket(options, clientContext -> {
                     if (clientContext.succeeded()) {
-                        LOG.debugf("Quinoa Dev WebSocket Client Connected: %s:%s%s", host, port, forwardUri);
+                        LOG.infof("Quinoa Dev WebSocket Client Connected: %s:%s%s", host, port, forwardUri);
```
Comment (melloware) [inline runtime/src/main/java/io/quarkiverse/quinoa/QuinoaDevWebSocketProxyHandler.java:71]: I made this an INFO because I like seeing when the HMR socket connects and plug it helps me in testing. Hope that is OK?

**Comment by melloware** [comment]
OK I have the Install and Restart buttons all wired up just need to figure out HOW to actually call something.

**Comment by melloware** [comment]
I switched to DRAFT until BETA2 comes out so I can just fix it all at once.

**Comment by melloware** [comment]
OK now that CR1 is out this is ready for review.

**Comment by melloware** [comment]
Getting an unrelated build failure "Build step io.quarkiverse.quinoa.deployment.QuinoaProcessor#prepareQuinoaDirectory threw an exception: java.lang.RuntimeException: Error in Quinoa while running package manager install command: pnpm install"

**Comment by melloware** [comment]
rebasing now.
